documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - 'docs/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'Cargo.toml'
          - 'Cargo.lock'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

source:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'
